spring:
  datasource:
    url: jdbc:mysql://localhost:3306/realstateapp?useSSL=false&serverTimezone=UTC
    username: your_username      # MySQL ??? ??
    password: your_password      # MySQL ????
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: update           # ?? ??? ?? ?? (create, update, validate, none ? ??)
    show-sql: true               # ???? SQL ?? ??
